export default {
  APP_NAME: "goleta inventory",
  APP_NAME_ABREVATED: "goleta",
  USERNAME: "username",
  PASSWORD: "password",
  EMAIL: "Email",
  EMAILS: "Emails",
  NO_EMAIL: "No Email",
  SIGN_IN: "sign in",
  WELCOME_MESSAGE: "Welcome back!",
  LOGIN_MESSAGE: "Log in to continue",
  NEXT: "Next",
  BACK: "Back",
  CONTINUE: "Continue",
  SAVE: "Save",
  SAVE_CHANGES: "Save Changes",
  CANCEL: "Cancel",
  UPDATE: "Update",
  CREATE: "Create",
  ACTIONS: "ACTIONS",
  ACTION: "ACTION",
  OPEN: "Open",
  REASON: "Reason",
  NOTE: "Note",
  ADD_NOTE: "Add Note",
  TYPE: "Type",
  CATEGORY: "Category",
  DASHBOARD: "Dashboard",
  REGISTRATIONS: "Registration",
  PRODUCTS: "Products",
  PAYMENTS: "Payments",
  FINANCE: "Finance",
  AUDITING: "Auditing",
  REPORT: "Report",
  REPORTS: "Reports",
  LOAN: "Loan",
  PAYROL: "Payroll",
  ADMIN: "Admin",
  SEARCH: "Search",
  ACCOUNTS: "Accounts",
  SEARCH_GL: "Search Gl",
  SEARCH_INDEX: "Search Index",
  TITLE: "title",
  HOUSE_NO: "House No",
  FULL_NAME: "Full Name",
  BASIC_DETAIL: "Basic detail",
  MORE_DETAIL: "More detail",
  OTHERS: "Others",
  IMAGE_EXPAND_INFO: "You can click the signature image below to expand.",
  ADDRESS: "Address",
  CUSTOMER_TYPE: "Customer Type",
  MOTHER_NAME: "MOTHER'S NAME",
  PHONE_NUMBER: "PHONE NUMBER",
  REGISTERED_ON: "Registered On",
  REGISTRATION_DATE: "reg date",
  OFFICE_TEL: "OFFICE TEL",
  ID_TYPE: "ID TYPE",
  ID_NUMBER: "ID No.",
  DATE_OF_ISSUE: "DATE OF ISSUE",
  EXPIRATION_DATE: "EXPIRATION DATE",
  DATE_OF_BIRTH: "DATE OF BIRTH",
  BIRTH_PLACE: "BIRTH PLACE",
  BIRTH: "Birth",
  MARITAL_STATUS: "MARITAL STATUS",
  DESCRIPTION: "DESCRIPTION",
  RELIGION: "RELIGION",
  POSITION: "POSITION",
  GENDER: "GENDER",
  TIN: "TIN",
  REGISTER: "REGISTER",
  CHOOSE_PHOTO: "Choose Photo",
  SELECT: "SELECT",
  SELECT_CUSTOMER: "SELECT CUSTOMER",
  IDENTITY: "Identity",
  HISTORY: "History",
  TEL: "Tel",
  PHONE: "PHONE",
  NAME: "Name",
  INDEX: "Index",
  STATUS: "Status",
  CODE: "Code",
  NOTES: "Notes",
  CENTS: "Cents",
  ACCOUNT_NO: "ACCOUNT NO.",
  ACC_NO: "Acc No.",
  TRIAL_BALANCE: "Trial Balance",
  DAILY_TRIAL_BALANCE: "Daily Trial Balance",
  DAILY_TRIAL_BALANCE_INFO: "Daily Trial Balance As Of",
  POSTING_JOURNAL: "Posting Journal",
  GL_REPORTS: "Gl Reports",
  GL_REPORTS_INFO: "GL posting journal as of",
  DATE: "Date",
  AMOUNT: "Amount",
  DIFFERENCE: "Difference",
  DEBIT: "Debit",
  DEBITS: "Debits",
  MAX_DEBITS: "Max Debits",
  CREDIT: "Credit",
  CREDITS: "Credits",
  MAX_CREDITS: "Max Credits",
  MAX_REPORTS: "Max Reports",
  TOTAL: "Total",
  BALANCE: "Balance",
  LOADING: "Loading",
  OFFICE: "Office",
  BRANCH: "Branch",
  BRANCHES: "Branches",
  BRANCH_NAME: "Branch Name",
  NEW_BRANCH: "New Branch",
  OFFICE_TYPE: "Office Type",
  SELECT_GL: "Select Gl",
  GL_STATEMENT: "Gl account statements",
  GL_DETAIL: "General Ledger Details",
  GL_NOT_FOUND: "oops gl record not found!",
  GL_NOT_FOUND_INFO: "Gl record can't be found. try again later!",
  CLASS: "Class",
  NEW_CLASS: "New General Ledger Class",
  VIEW_MODE: "View Mode",
  TRIAL_BALANCE_INFO: "Trial Balance Untill",
  SELECT_DATE: "Select Date",
  CASH_POSITION: "Cash Position",
  CASH_POSITION_INFO: " Cash position report as of",
  CASH_POSITION_PAST_INFO:
    "To view past daily operations, you should have to select a date.",
  NO_OPENED_TIILS_MESSAGE: "No tills were opened.",
  FROM: "From",
  TO: "To",
  SIDE: "Side",
  COA_HR_MODE_INFO: "Chart of accounts in heirarchical view",
  AUDIT: "Audit",
  DISCREPANT: "Discrepant",
  EXACT: "Exact",
  AUDIT_OVERVIEW_INFO: "Overview of auditing",
  AUDITED: "Audit",
  UNAUDIT: "Unaudit",
  UNAUDITED: "Unaudited",
  DEPOSIT_TRANSACTIONS: "Deposit transactions",
  DEPOSIT: "Deposit",
  WITHDRAW: "Withdraw",
  TRANSFER: "Transfer",
  WITHDRAWAL_TRANSACTIONS: "Withdrawal transactions",
  TRANSFER_TRANSACTIONS: "Transfer transactions",
  AUDIT_RESULT: "Audit Result",
  SENDER: "Sender",
  RECEIVER: "Receiver",
  VERIFY: "Verify",
  DELETE: "Delete",
  EDIT: "Edit",
  DEPOSIT_FORM: "Deposit Form",
  WITHDRAW_FORM: "Withdraw Form",
  MANUAL_WITHDRAW_FORM: "Manual Gl Withdraw Form",
  MANUAL_DEPOSIT_FORM: "Manual Gl Deposit Form",
  TRANSFER_FORM: "Transfer Form",
  FILL_FORM_PROPORLY: "Fill in the form properly",
  PAYMENT_STARTING_DATE: "Payment Starting Date",
  TOTAL_TERMS: "Total Terms",
  INTEREST_RATE: "Interest Rate",
  PARENT: "Parent",
  NEW_LEAF: "New Leaf",
  ALLOW_MANUAL_TRANS: "Allow manual transactions",
  ALLOW_MANUAL_TRANS_INFO:
    "Turn it on to allow manual transactions on this general ledger.",
  ALLOW_DEBIT_CREDIT: "Allow DEBIT/CREDIT",
  ALLOW_DEBIT_CREDIT_INFO:
    "Turn it on to allow debit/credit transactions on this general ledger.",
  SET_HO_ACCOUNT: "Set as branch's account on head office",
  SET_HO_ACCOUNT_INFO:
    "Turn it on to set this general ledger account as a branch account to hold its balance in head office.",
  HOLIDAYS: "Holidays",
  HOLIDAY: "Holiday",
  NEW_HOLIDAY: "New Holiday",
  HOLIDAY_NAME: "Holiday Name",
  START_DATE: "Start Date",
  END_DATE: "End Date",
  REPAYMENT_RULE: "Repayment Rule",
  ORGANIZATION: "Organization",
  ORGANIZATION_DETAIL: "Organization Detail",
  EDIT_ORG_DETAIL: "Edit organization basic details",
  EDIT_ORG_ADDRESS: "Edit organization address",
  SLOGAN: "Slogan",
  APP: "App Name",
  NOT_ADDED: "Not added",
  CREATED_AT: "Created At",
  POBOX: "Pobox",
  KEBELE: "Kebele",
  SUB_TOWN: "Sub-Town",
  MODULES: "Modules",
  LOGO: "Logo",
  SLIP_LOGO: "Slip Logo",
  CONTACTS: "Contacts",
  COLOR_AND_THEME: "colors and theme preferences",
  PRIMARY_COLOR: "Primary Color",
  SECONDARY_COLOR: "Secondary Color",
  AUTO_VERIFICATION: "Auto Verification",
  SESSION_TIMEOUT: "Session time out (in min)",
  SESSION_TIMEOUT_INFO: "Hint: max time out is 20 min",
  TRANS: "Trans",
  MAX_TRANS: "max number of trans",
  OUTSTANDING_AMOUNT: "Outstanding Amount",
  ENTER_TO_SEARCH: "Hit ENTER to search",
  SEARCH_TYPE: "Search Type",
  SEARCH_CRITERIA: "Search Criteria",
  FILTER_RESULT: "Filter Result",
  FILTER_BY_STATUS: "Filter by status",
  FILTER_BY_DATE: "Filter by registration date",
  GENERAL: "General",
  ADDITIONAL_INFO: "Additional Information",
  FAMILY_MEMBERS: "Family Members",
  SAVING_ACCOUNTS: "Saving Accounts",
  CASH: "CASH",
  NON_CASH: "NON-CASH",
  PARENT_TILL: "Parent Till",
  REQUIRES_PARENT_TILL: "Requires parent till opening",
  REQUIRES_PARENT_TILL_INFO:
    "Parent till should be opened in order to open this till.",
  REQUIRES_VERIFICATION: "Requires verification",
  REQUIRES_VERIFICATION_INFO:
    "There must be a verification by an officer who has booked its parent till.",
  AMOUNT_IN_DENOMINATION: "Amount in denomination",
  AMOUNT_IN_DENOMINATION_INFO:
    "The amount that will be added to and subtracted from this till/vault should be in denomination.",
  PERMISSIONS: "Permissions",
  INTER_BRANCH: "inter-branch",
  HOME_BRANCH: "Home branch",
  OTHERS_ON_US: "others on us",
  SELECT_OFFICE: "Select Office",
  MAX_TILLS_ALLOWED: "max tills allowed",
  MAX_BRANCHES_ALLOWED: "max branches allowed",
  SEE_MORE: "See More",
  SEE_MORE_INFO: "You can click the button shown below to see full detail.",
  TRID: "tr. id",
  TIME: "Time",
  B_BALANCE: "b.Balance",
  E_BALANCE: "e.Balance",
  PERFORMED_BY: "Performed By",
  TRANSACTIONS: "Transactions",
  MAKER: "Maker",
  CHECKER: "Checker",
  SELECT_TYPE: "Select Type",
  MANUAL: "Manual",
  MANDATORY_SAVING: "Mandatory saving?",
  TERM_DEPOSIT: "Term deposit?",
  AUTO_CREATE_SHARE: "Auto create share account?",
  SELECT_PRODUCT_CATAGORY: "Select product category",
  CURRENT_TERM: "Current Term",
  REPAYMENT: "Repayment",
  REMAINING: "Remaining",
  PAY_VIA_CASH: "Pay via cash?",
  PAY_VIA_CASH_INFO:
    "The payment is made in person. i.e. the payee should provide it in hard cash.",
  BANK_PAYMENT: "Bank payment?",
  BANK_PAYMENT_INFO: "The payment is made in banks.",
  CHANGE_LANGUAGE: "Change Language",
  INPUT: "Input",

  MY_ORGANIZATION: "My Organization",
  USER_GROUPS: "User Groups",
  USERS: "Users",
  CLASSES: "Classes",
  LEAVES: "Leaves",
  HIERARCHICAL: "Hierarchical",
  SAVING_CATEGORIES: "Saving Categories",
  SHARE_CATEGORIES: "Share Categories",
  OVERVIEW: "Overview",
  AUTHORIZE_TRXNS: "Authorize Trxns",

  tig: "ትግ",
  en: "EN",
  PAYROLL: "Payroll",
  AUTH: "Auth",
  GL: "GL",
  COUNT: "Count",
  ATTENDANCE: "Attendance",
  CONFIG: "Config",
  DEPARTMENT: "Department",
  EMPLOYEE: "Employee",
  EMPLOYEES: "Employees",
  ADD_EMPLOYEE: "Add Employee",
  SALARY: "Salary",
  SALARIES: "Salaries",
  SCALE: "Scale",
  JOB_TITLE: "Job Title",
  DEPOSITES: "Deposites",
  WITHDROWS: "Withdrows",
  PROFILE: "Profile",
  PERMANENT: "Permanent",
  GROSS_SALARY: "Gross Salary",
  SCALE_SALARY: "Scale Salary",
  SCALES: "Scale",
  TAX_INCOME: "Tax Income",
  PENSION_RETIREMENT: "Pension Retirement",
  COMPONENT: "Wage",
  COMPONENTS: "Wages",
  Component: "Wage",
  Components: "Wages",
  EMPLOYEE_COMPONENT: "Employee Wages",
  ACTIVITY_LOG: "Activities",
  ALL_TIME: "All time",
  THIS_YEAR: "This year",
  THIS_MONTH: "This month",
  PRINT: "Print",
  Actions: "Actions",
  SHOW: "Show",
  Verified: "Verified",
  Status: "Status",
  Earning: "Earning",
  Regular: "Regular",
  "Rate Type": "Rate Type",
  Amount: "Amount",
  Taxable: "Taxable",
  Week: "Week",
  Biweek: "Biweek",
  Month: "Month",
  Year: "Year",
  Date: "Date",
  Type: "Type",
  Add: "Add",
  Payrolls: "Payrolls",
  10: "10",
  Payroll: "Payroll",
  Settings: "Settings",
  "Log out": "Log out",
  Office: "Office",
  Active: "Active",
  Given: "Given",
  Pending: "Pending",
  GRADE: "GRADE",
  BASIC_SALARY: "BASIC SALARY",
  HARDSHIP: "HARDSHIP",
  HARDSHIP_RATE: "HARDSHIP RATE",
  HARDSHIP_ALLOWANCE: "HARDSHIP ALLOWANCE",
  ACCOUNT_NUMBER: "ACCOUNT NUMBER",
  ARREARS_BALANCE: "ARREARS BALANCE",
  "ARREARS BALANCE": "ARREARS BALANCE",
  ID: "ID",
  CHANGE_STATUS: "Change status",
  TERMINATE: "Terminate",
  RUN_PAYROLL: "RUN PAYROLL",
  CHANGE_DEPARTMENT: "Change department",
  CHANGE_JOB_TITLE: "Change job title",
  CHANGE_SCALE: "Change scale",
  "PAYROLL HISTORY": "PAYROLL HISTORY",
  "PAYMENT HISTORY": "Payment history",
  ACTIVITY: "Activity",
  Save: "Save",
  Profile: "Profile",
  "Full Name": "Full Name",
  "Employee ID": "Employee ID",
  "Account Number": "Account Number",
  "Phone Number": "Phone Number",
  Dob: "Dob",
  Sex: "Sex",
  Male: "Male",
  Female: "Female",
  "Is Permanent": "Is Permanent",
  "Employment Date": "Employment Date",
  Department: "Department",
  "Job Title": "Job Title",
  Scale: "Scale",
  "General Ledger": "General Ledger",
  Percentile: "Percentile",
  Flat: "Flat",
  "Is Earning": "Is Earning",
  "Is Regular": "Is Regular",
  "Office Specific": "Office Specific",
  "Is Individual": "Is Individual",
  "Is DEPARTMENT SPECIFIC": "Is Department Specific",
  "Is Title Specific": "Is Title Specific",
  "Is GRADE Specific": "Is Grade Specific",
  "Is Scale Specific": "Is Scale Specific",
  "Is Time Bound": "Is Time Bound",
  "Is Permanent Only": "Is Permanent Only",
  "Has Upper Limit": "Has Upper Limit",
  Offices: "Offices",
  "Add Office": "Add Office",
  Region: "Region",
  CITY: "CITY",
  City: "CITY",
  "Specific Address": "Specific Address",
  "COST CENTER": "COST CENTER",
  "PROFIT CENTER": "PROFIT CENTER",
  BANK: "BANK",
  Bank: "BANK",
  Moto: "Moto",
  "Bank Account Number": "Bank Account Number",
  NO_DATA_FOUND: "No record",
  Name: "Name",
  Reverse: "Reverse",
  Search: "Search",
  "Net Salary": "Net Salary",
  TAXABLE_INCOME: "Taxable income",
  DEDUCTIONS: "Deductions",
  OverTime: "Overtime",
  "Pension R": "Pension R",
  "EMPLOYEE P": "Employee P",
  "EMPLOYER P": "Employer P",
  Tax: "Tax",
  "B Salary": "B Salary",
  Salaries: "Salaries",
}
