export default {
  APP_NAME: "",
  APP_NAME_ABREVATED: "",
  USERNAME: "መለለዪ ስም",
  PASSWORD: "መሕለፊ ቃል",
  EMAIL: "ኢ-መይል",
  EMAILS: "ኢ-መይላት",
  NO_EMAIL: "ኢ-መይል የለን",
  SIGN_IN: "ይእተዉ",
  WELCOME_MESSAGE: "እንኳዕ ብደሓን መፁ!",
  LOGIN_MESSAGE: "ስራሕ ንምቕፃል ይእተዉ",
  NEXT: "ቀፃሊ",
  BACK: "የመለሱ",
  CONTINUE: "ይቐፅሉ",
  SAVE: "ይዓቅቡ",
  SAVE_CHANGES: "ለውጥታት ይዓቅቡ",
  CANCEL: "ይሰርዙ",
  UPDATE: "የማሓይሹ",
  CREATE: "ይፍጠሩ",
  ACTIONS: "ተግባራት",
  ACTION: "ተግባር",
  OPEN: "ይኽፈቱ",
  REASON: "ምኽንያት",
  NOTE: "መዘኻኻሪ",
  ADD_NOTE: "መዘኻኻሪ ይወስኹ",
  TYPE: "ዓይነት",
  CATEGORY: "ምድብ",
  MIN: "ዝነኣሰ",
  MAX: "ዝለዓለ",
  DASHBOARD: "ዋና ገፅ",
  REGISTRATIONS: "ምዝገባ",
  PRODUCTS: "Products",
  PAYMENTS: "ክፍሊታት",
  FINANCE: "ፋይናንስ",
  AUDITING: "ኦዲት ምግባር",
  REPORT: "ሪፖርት",
  REPORTS: "ሪፖርት",
  LOAN: "ልቓሕ",
  PAYROL: "ፐይሮል",
  ADMIN: "ኣመሓዳሪ",
  SEARCH: "ይኣልሹ",
  ACCOUNTS: "ሒሳባት",
  ACCOUNT_DETAILS: "ናይ ሒሳብ ዝርዝር ሓበሬታ",
  ACCOUNT_DETAIL_INFO:
    "ናይ ሒሳብ ዝርዝር ሓበሬታ ንምርኣይ ሒሳብ ቁፅሪ ኣእትዮም Enter ዝብል ቁልፊ ይፀዓኑ።",

  NO_ACCOUNT_DETAIL: "ናይ ሒሳብ ዝርዝር ሓበሬታ ኣይተረኸበን።",
  ACCOUNT_STATEMENT: "ናይ ሒሳብ ዝርዝር ኣታውን ወፃእን",
  FUNDS_RESERVED: "ናይ ሒሳብ ዝርዝር እገዳታት",
  RESERVE_FUND: "ሒሳብ ይኣግዱ",
  FUNDS_RESERVED_STATEMENT: "ናይ ሒሳብ ዝርዝር እገዳታት",
  RELEASE: "ይልቅቑዎ",
  DEVIDEND_LOGS: "ናይ መቐሎ ዝርዝር መዝገብ",
  ACCOUNT_NAME: "ሽም ሒሳብ",
  ACCOUNT_HOLDER: "በዓል ዋና ሒሳብ",
  ACCOUNT_REGISTRATION_FORM: "ናይ ሒሳብ መመዝገቢ ቅጥዒ",
  NEW_ACCOUNT: "ሓዱሽ ሒሳብ",
  ACCOUNT_INFO: "ናይ ሒሳብ ሓበሬታ",
  NEW_ACCOUNT_INFO: "ሓዱሽ ሒሳብ ይመዝግቡ",
  CUSTOMER: "ዓሚል",
  CUSTOMERS: "ዓማዊል",
  CUSTOMER_DETAIL: "ናይ ዓሚል ዝርዝር ሓበሬታ",
  NEW_CUSTOMER: "ሓዱሽ ዓሚል",
  NEW_CUSTOMER_INFO: "ሓዱሽ ዓሚል ይመዝግቡ",
  GENERAL_CUST_INFO: "ሓፈሻዊ ናይ ዓሚል ሓበሬታ",
  GENERAL_ACCOUNT_INFO: "ሓፈሻዊ ናይ ሒሳብ ሓበሬታ",
  SHARES: "ዕፃታት",
  SHARE: "ዕፃ",
  SHARE_ACCOUNTS: "ናይ ዕፃ ሒሳብ",
  NEW_SHARE: "ሓዱሽ ናይ ዕፃ ሒሳብ",
  VAULTS: "ካዝናታት",
  VAULT: "ካዝና",
  NEW_VAULT: "ሓዱሽ ካዝና ይወስኹ",
  TILLS: "ናይ ኣገልግሎት መስኮታት",
  TILL: "ናይ ኣገልግሎት መስኮት",
  SELECT_TILL: "ናይ ኣገልግሎት መስኮት ይምረፁ",
  SELECT_AND_OPEN_TILLS: "ናይ ኣገልግሎት መስኮታት መሪፆም ይኽፈቱ",
  NO_TILL_LEFT: "ዘይተኸፈተ ዝተረፈ ናይ ኣገልግሎት መስኮት የለን",
  NEW_TILL: "ሓዱሽ ናይ ኣገልግሎት መስኮት ይወስኹ",
  CURRENCY: "መተዓዳደጊ ገንዘብ",
  CURRENCIES: "መተዓዳደግቲ ገንዘብ",
  NEW_CURRENCY: "ሓዱሽ መተዓዳደጊ ገንዘብ ይወስኹ",
  PAYMENT_MODES: "ኣግባባት ክፍሊት",
  PAYMENT_MODE: "ኣግባብ ክፍሊት",
  PAYMENT_TYPE: "ዓይነት ክፍሊት",
  NEW_PAYMENT_MODE: "ሓዱሽ ኣግባብ ክፍሊት ይወስኹ",
  BANKS: "ባንክታት",
  BANK: "ባንኪ",
  BANK_NAME: "ሽም ባንኪ",
  SELECT_BANK: "ባንኪ ይምረፁ",
  NEW_BANK: "ሓዱሽ ባንኪ ይወስኹ",
  DOCUMENTS: "ሰነዳት",
  NEW_DOCUMENT: "ሓዱሽ ሰነድ",
  DOCUMENT_NAME: "ናይ ሰነድ ሽም",
  DOCUMENT_CODE: "ናይ ሰነድ ኮድ",
  SYSTEM_CODE: "ናይ ሲስተም ኮድ",
  SHELF_NUMBER: "ቁፅሪ መደርደሪ ሳፁን",
  FILE_TYPE: "ዓይነት ፋይል",
  PRODUCT_DETAIL: "product details",
  PRODUCT_CATEGORY: "Product Category",
  NEW_PRODUCT_CATEGORY: "New Saving Product Category",
  SHARE_PRODUCTS: "Share Products",
  NEW_SHARE_PRODUCTS: "New Share Product",
  PRODUCT_TYPES: "Product Types",
  NEW_PRODUCT_TYPES: "Add New Product Type",
  CHARGES: "ቅፅዓታት",
  SELECT_CHARGES: "ቅፅዓታት ይምረፁ",
  CHARGE: "ቅፅዓት",
  EDIT_CHARGE: "ቅፅዓት የስተኻኽሉ",
  DELETE_CHARGE: "ቅፅዓት የጥፍኡ",
  VERIFY_CHARGE: "ቅፅዓት የፅድቑ",
  CHANGE_STATUS_CHARGE: "ኩነት ይለውጡ",
  NEW_CHARGE: "ሓዱሽ ቅፅዓት ይወስኹ",
  SEARCH_CUSTOMER: "ዓሚል ይኣልሹ",
  SEARCH_ACCOUNT: "ሒሳብ ይኣልሹ",
  SEARCH_DOCUMENT: "ሰነድ ይኣልሹ",
  SEARCH_GL: "GL ይኣልሹ",
  SEARCH_SHARE_ACCOUNT: "ናይ ዕፃ ሒሳብ ይኣልሹ",
  SEARCH_INDEX: "ብመድለዪ ይኣልሹ",
  TITLE: "ርእሲ",
  HOUSE_NO: "ገዛ ቁፅሪ",
  FULL_NAME: "ሙሉእ ሽም",
  BASIC_DETAIL: "መሰረታዊ ዝርዝር",
  MORE_DETAIL: "ተወሳኺ ዝርዝር",
  OTHERS: "ካልኦት",
  EDUCATION_INFO: "ትምህርታዊ ሓበሬታን ምቑፃርን",
  IMAGE_EXPAND_INFO: "ንምስፋሕ ኣብ ታሕቲ ዘሎ ናይ ፊርማ ምስሉ ይፀዓኑ።",
  SIGNATURE: "ፊርማ",
  ADDRESS: "ኣድራሻ",
  EMERGENCY_CONTACTS: "ናይ ሓደጋ ጊዜ ተፀዋዒ",
  SIGNATURE_AND_PHOTO: "ፊርማን ፎቶን",
  CUSTOMER_TYPE: "ዓይነት ዓሚል",
  MOTHER_NAME: "ሽም ኣዶ",
  PHONE_NUMBER: "ስልኪ ቁፅሪ",
  REGISTERED_ON: "ዝተመዝገቡሉ፡ ",
  REGISTRATION_DATE: "ዝተመዝገቡሉ ዕለት፡ ",
  OFFICE_TEL: "ናይ ቢሮ ስልኪ ቁፅሪ",
  ID_TYPE: "ዓይነት መለለዪ መንነት",
  ID_NUMBER: "ቁፅሪ መለለዪ መንነት",
  DATE_OF_ISSUE: "ዝወፀሉ ዕለት",
  EXPIRATION_DATE: "ዘብቀዐሉ ዕለት",
  DATE_OF_BIRTH: "ናይ ትውልዲ ዕለት",
  BIRTH_PLACE: "ናይ ትውልዲ ቦታ",
  BIRTH: "ትውልዲ",
  MARITAL_STATUS: "ናይ ሓዳር ኩነታት",
  SIGHT_DISABLED: "ምርኣይ ዝተስኣኖ",
  DESCRIPTION: "ገለፃ",
  RELIGION: "ሃይማኖት",
  POSITION: "ናይ ስራሕ ደረጃ",
  GENDER: "ፆታ",
  OCCUPATION: "ሞያ",
  TIN: "ናይ ግብሪ ከፋሊ መለለዪ ቁፅሪ",
  EDUCATION_LEVEL: "ደረጃ ትምህርቲ",
  NUM_OF_CHILDREN: "በዝሒ ውላድ",
  COUNTRY: "ሃገር",
  STATE: "ክልል",
  CURRENT_ADDRESS: "ናይ ሐዚ ኣድራሻ",
  RELATIVES: "ኣዝማድ",
  REGISTER: "ይመዝግቡ",
  CHOOSE_PHOTO: "ፎቶ ይምረፁ",
  CHOOSE_SIGNATURE: "ፊርማ ይምረፁ",
  PERSON: "ሰብ",
  GROUP: "ጉጅለ",
  COMPANY: "ትካል",
  SELECT: "ይምረፁ",
  SELECT_CUSTOMER: "ዓሚል ይምረፁ",
  CUSTOMER_ID: "ናይ ዓሚል መለለዪ ቁፅሪ",
  NUM_OF_SHARES: "በዝሒ ዕፃ",
  SAVING_AMOUNT: "ናይ ዕቋር ሒሳብ",
  INITIAL_BALANCE: "መበገሲ ቀሪ ሒሳብ",
  IDENTITY: "መለለዪ",
  HISTORY: "ሕሉፋት ዝተፈፀሙ ሒሳባት",
  TEL: "ስልኪ ቁፅሪ",
  PHONE: "ስልኪ ቁፅሪ",
  NAME: "ሽም",
  SHORT_NAME: "ሓፂር ሽም",
  INDEX: "መፍለዪ",
  STATUS: "ኩነት",
  CODE: "ኮድ",
  NOTES: "ማስታወሻ",
  CENTS: "ሳናቲም",
  ACCOUNT_NO: "ቁፅሪ ሒሳብ",
  ACCOUNT_NUMBER: "ቁፅሪ ሒሳብ",
  ACC_NO: "ቁፅሪ ሒሳብ",
  CUSTOMER_NO: "ናይ ዓሚል ቁፅሪ",
  GL_LINK: "መራኸቢ GL",
  SHARE_UPGRADE_REQUEST: "ዕፃ መወሰኺ ሕቶታት",
  SHARE_DOWNGRADE_REQUEST: "ዕፃ መቐነሲ ሕቶታት",
  SHARE_HISTORY_INFO: "ዝተፈፀሙ ሕሉፋት  ናይ ወሰኽ ወይ ቕናሽ ዕፃታት",
  TRIAL_BALANCE: "ግዝያዊ ቀሪ ሒሳብ",
  DAILY_TRIAL_BALANCE: "ዕለታዊ ግዝያዊ ቀሪ ሒሳብ",
  DAILY_TRIAL_BALANCE_INFO: "ዕለታዊ ግዝያዊ ቀሪ ሒሳብ ካብ ዕለት፡ ",
  POSTING_JOURNAL: "ናይ ሒሳብ ዝርዝር ምምዝጋብ",
  GL_REPORTS: "ናይ GL ሒሳባት ሪፖርት",
  GL_REPORTS_INFO: "ናይ GL ሒሳባት ዝርዝር መዝገብ ካብ ዕለት",
  DATE: "ዕለት",
  AMOUNT: "መጠን",
  DIFFERENCE: "ኣፈላላይ",
  DEBIT: "ተቐናሲ",
  DEBITS: "ተቐነስቲ",
  MAX_DEBITS: "ዝለዓሉ ተቐነስቲ",
  CREDIT: "ቀሪ",
  CREDITS: "ቀሪታት",
  MAX_CREDITS: "ዝለዓሉ ቀሪታት",
  MAX_REPORTS: "ዝለዓሉ ሪፖርታት",
  TOTAL: "ድምር",
  BALANCE: "ቀሪ ሒሳብ",
  LOADING: "ይፅዕን ኣሎ",
  OFFICE: "ቢሮ",
  BRANCH: "ቅርንጫፍ",
  BRANCHES: "ቅርንጫፋት",
  BRANCH_NAME: "ሽም ቅርንጫፍ",
  NEW_BRANCH: "ሓዱሽ ቅርንጫፍ",
  OFFICE_TYPE: "ዓይነት ቢሮ",
  SELECT_GL: "GL ምረፅ",
  GL_STATEMENT: "ናይ Gl ሒሳብ ኣታውን ወፃእን ዝርዝር",
  GL_DETAIL: "GL ዝርዝር",
  GL_NOT_FOUND: "ይቕርታ! ናይ GL መዝገብ ኣይተረኸበን!",
  GL_NOT_FOUND_INFO: "Gl መዝገብ ኣይተረኸበን፤ ፀኒሖም ይሞክሩ!",
  CLASS: "መደብ",
  NEW_CLASS: "ሓዱሽ ናይ GL መደብ",
  VIEW_MODE: "መርኣዪ ሜላ",
  TRIAL_BALANCE_INFO: "ግዝያዊ ቀሪ ሒሳብ ክሳብ",
  SELECT_DATE: "ዕለት ይምረፁ",
  CASH_POSITION: "ናይ ጥረ ገንዘብ ቀሪ ሒሳብ",
  CASH_POSITION_INFO: " ናይ ጥረ ገንዘብ ቀሪ ሒሳብ ካብ",
  CASH_POSITION_PAST_INFO: "ሕሉፍ መዓልታዊ ናይ ሒሳብ ምንቅስቓሳት ንምርኣይ እንተደልዮም መዓልቱ ይምረፁዎ",
  NO_OPENED_TIILS_MESSAGE: "ናይ ክፍሊት መስኮታት ኣይተኸፈቱን!",
  FROM: "ካብ",
  TO: "ናብ",
  SIDE: "ገፅ",
  COA_HR_MODE_INFO: "ናይ ሒሳብ ቻርት ብደረጃ እንትረአ",
  AUDIT: "ኦዲት",
  DISCREPANT: "ፍልልይ",
  EXACT: "ብትኽክል",
  AUDIT_OVERVIEW_INFO: "ሓፈሻዊ ናይ ኦዲት ሓበሬታ",
  AUDITED: "ኦዲት",
  UNAUDIT: "ናብ ኦዲት ዘይተገብሩ ይመልሱ",
  UNAUDITED: "ኦዲት ዘይተገበረ",
  DEPOSIT_TRANSACTIONS: "ናይ ኣታዊ ሒሳብ ምንቅስቓሳት",
  DEPOSIT: "ኣታዊ ይግበሩ",
  WITHDRAW: "ወፃኢ ይግበሩ",
  TRANSFER: "የመሓላልፉ",
  WITHDRAWAL_TRANSACTIONS: "ናይ ወፃኢ ሒሳባት ምንቅስቓስ",
  TRANSFER_TRANSACTIONS: "ናይ ምትሕልላ ሒሳባት ምንቅስቓስ",
  AUDIT_RESULT: "ናይ ኦዲት ውፅኢት",
  SENDER: "ለኣኺ",
  RECEIVER: "ተቐባሊ",
  SENDER_ACCOUNT_NUMBER: "ናይ ለኣኺ ቁፅሪ ሒሳብ",
  RECEIVER_ACCOUNT_NUMBER: "ናይ ተቐባሊ ቁፅሪ ሒሳብ",
  TILL_HISTORY: "ናይ ግልጋሎት መስኮት ሕሉፋት ሒሳባት ዝርዝር",
  VERIFY: "የፅድቑ",
  DELETE: "የውግዱ",
  EDIT: "የመሓይሹ",
  DEPOSIT_FORM: "ኣታዊ መግበሪ ቅጥዒ",
  WITHDRAW_FORM: "ወፃኢ መግበሪ ቅጥዒ",
  MANUAL_WITHDRAW_FORM: "ናይ ማንዋል GL ወፃኢ መግበሪ ቅጥዒ",
  MANUAL_DEPOSIT_FORM: "ናይ ማንዋል GL ኣታዊ መግበሪ ቅጥዒ",
  TRANSFER_FORM: "ሒሳብ መሕለፊ ቅጥዒ",
  SHARE_WITHDRAW_FORM: "ዕፃ ወፃኢ መግበሪ ቅጥዒ",
  FILL_FORM_PROPORLY: "ነዚ ቅጥዒ ብኣግባቡ ተጠንቂቖም ይምልኡዎ",
  PAYMENT_STARTING_DATE: "ክፍሊት ዝጅመረሉ ዕለት",
  TOTAL_TERMS: "ጠቕላላ ስምምዕነት",
  INTEREST_RATE: "ናይ ወለድ ሬት",
  PARENT: "ወላዲ",
  NEW_LEAF: "ሓዱሽ ጫፍ",
  ALLOW_MANUAL_TRANS: "ማኑዋል ምንቅስቓሳት ሒሳብ ይፍቀዱ",
  ALLOW_MANUAL_TRANS_INFO:
    "ኣብዚ ናይ GL ሒሳብ ማኑዋል ምንቅስቓሳት ንምፍቃድ ናይ መቆፃፀሪ ቁልፉ ይወልዑ።",
  ALLOW_DEBIT_CREDIT: "ኣታዊ/ወፃኢ ይፍቀዱ",
  ALLOW_DEBIT_CREDIT_INFO:
    "ኣብዚ ናይ GL ሒሳብ ናይ ኣታዊ/ወፃኢ ምንቅስቓሳት ንምፍቃድ ናይ መቆፃፀሪ ቁልፉ ይወልዑ።",
  SET_HO_ACCOUNT: "ነዚ ሒሳብ ከም ናይዚ ቅርንጫፍ ሒሳብ ገይሮም ኣብቲ ዋና ቢሮ  የቐምጡ",
  SET_HO_ACCOUNT_INFO:
    "ነዚ GL ሒሳብ ኣብ ዋና ቢሮ ናይዚ ቅርንጫፍ ቀሪ ሒሳብ መትሐዚ ሒሳብ ኮይኑ ንኸገልግል ነዚ መአዘዚ ቁልፊ ይፀዓኑ።",
  HOLIDAYS: "በዓላት",
  HOLIDAY: "በዓል",
  NEW_HOLIDAY: "ሓዱሽ በዓል",
  HOLIDAY_NAME: "ሽም በዓል",
  START_DATE: "መጀመሪ በዓል",
  END_DATE: "መፈፀምታ ዕለት",
  REPAYMENT_RULE: "ዕዳ መኽፈሊ ሕጊ",
  ORGANIZATION: "ትካል",
  ORGANIZATION_DETAIL: "ናይዚ ትካል ዝርዝር ሓበሬታ",
  EDIT_ORG_DETAIL: "ናይዚ ትካል መሰረታዊ ዝርዝር ሓበሬታ የስተኻኽሉ",
  EDIT_ORG_ADDRESS: "ናይዚ ትካል ኣድራሻ የስተኻኽሉ",
  SLOGAN: "ጭርሖ",
  APP: "ሽም መተግበሪ",
  NOT_ADDED: "ኣይተወሰኸን",
  CREATED_AT: "ዝተፈጠረሉ ዕለት",
  POBOX: "ፖ.ሳ.ቁ.",
  KEBELE: "ጣብያ",
  SUB_TOWN: "ዕሸል ከተማ",
  MODULES: "ሞጁላት",
  LOGO: "ሎጎ",
  SLIP_LOGO: "ናይ ሎጎ ስሊፕ",
  CONTACTS: "ተፀዋዕቲ",
  COLOR_AND_THEME: "ናይ ሕብርን መልክዕን ምርጫታት",
  PRIMARY_COLOR: "ቀዳማይ ሕብሪ",
  SECONDARY_COLOR: "ካልኣይ ሕብሪ",
  AUTO_VERIFICATION: "ዓርሰ-ምርግጋፅ",
  AUTO_VERIFICATION_INFO:
    "ናይ ዓማዊል፣ ሒሳባት፣ ዕፃታት፣ ምህርቲ መደባት፣ ቮልትታት ወዘተ ምዝገባታት ብዓርሰ-ምርግጋፅ ክኾን ምግባር።",
  SESSION_TIMEOUT: "ክፍለ-ጊዜ ተወዲኡ (ብደቓይቕ)",
  SESSION_TIMEOUT_INFO: "ሓበሬታ: እቲ ዝለዓለ መወድኢ ግዜ 20 ደቓይቕ እዩ።",
  TRANS: "ምንቅስቓሳት",
  MAX_TRANS: "ዝለዓለ በዝሒ ምንቅስቓሳት ሒሳብ",
  OUTSTANDING_AMOUNT: "ዘይወፀ ቀሪ ሒሳብ",
  ENTER_TO_SEARCH: "ንምእላሽ ENTER ዝብል ቁልፊ ይፀዓኑ።",
  SEARCH_TYPE: "ናይ ዝእለሹ ዓይነታት",
  SEARCH_CRITERIA: "መአለሺ ረቛሕታት",
  FILTER_RESULT: "ዝፀረየ ውፅኢት ይኣልሹ",
  FILTER_BY_STATUS: "ዝፀረየ ውፅኢት ብኩነት ይኣልሹ",
  FILTER_BY_DATE: "ዝፀረየ ውፅኢት ብመመዝገቢ ዕለት ተጠቒሞም ይኣልሹ።",
  GENERAL: "ሓፈሻዊ",
  ADDITIONAL_INFO: "ተወሳኺ ሓበሬታ",
  FAMILY_MEMBERS: "ኣባላት ስድራ ቤት",
  SAVING_ACCOUNTS: "ናይ ዕቋር ሒሳብ",
  LOAN_ACCOUNTS: "ናይ ልቓሕ ሒሳብ",
  CASH: "ጥረ-ገንዘብ",
  NON_CASH: "ጥረ-ገንዘብ ዘይኮነ",
  PARENT_TILL: "ላዕለዋይ-ቲል",
  REQUIRES_PARENT_TILL: "ላዕለዋይ-ቲል ይኽፈቱ።",
  REQUIRES_PARENT_TILL_INFO: "ነዚ ቲል ንምኽፋት መጀመርያ ላዕለዋይ-ቲል ይኽፈቱ።",
  REQUIRES_VERIFICATION: "ምርግጋፅ ይጠልብ",
  REQUIRES_VERIFICATION_INFO: "ነዚ ቲል ቅድሚ ምሓዞም ላዕለዋይ-ቲል ዝሓዘ ኦፊሰር ከረጋግፆ ኣለዎ።",
  AMOUNT_IN_DENOMINATION: "ኣብ ዝርዝር ገንዘብ ዝርከብ ቀሪ ሒሳብ",
  AMOUNT_IN_DENOMINATION_INFO:
    "ናብ/ካብ ቲል/ቮልት ውሽጢ ዝውሰኽ/ዝቕነስ መጠን ገንዘብ ኣብ ዝርዝር ገንዘብ ክቕመጥ ኣለዎ።",
  PERMISSIONS: "ፍቓዳት",
  INTER_BRANCH: "ኣብ ሞንጎ ቅርንጫፋት",
  HOME_BRANCH: "ናይ ባዕልኻ ቅርንጫፍ",
  OTHERS_ON_US: "ካልኦት ኣብ ባዕልና",
  SELECT_OFFICE: "ቢሮ ይምረፁ",
  MAX_TILLS_ALLOWED: "ዝፍቀዱ ዝለዓሉ በዝሒ ቲላት",
  MAX_BRANCHES_ALLOWED: "ዝፍቀዱ ዝለዓሉ በዝሒ ቅርንጫፋት",
  SEE_MORE: "ተወሳኺ ንምርኣይ",
  SEE_MORE_INFO: "ሙሉእ ዝርዝር ንምርኣይ ኣብ ታሕቲ ዘሎ ቁልፊ ይፀዓኑ።",
  TRID: "tr. id",
  TIME: "ግዜ",
  B_BALANCE: "መበገሲ ቀሪ ሒሳብ",
  E_BALANCE: "መዛዘሚ ቀሪ ሒሳብ",
  PERFORMED_BY: "ፈፃሚ",
  TRANSACTIONS: "ምንቅስቓሳት",
  MAKER: "መዳለዊ",
  CHECKER: "መረጋገፂ",
  SELECT_TYPE: "ዓይነት ይምረፁ",
  MANUAL: "ማኑዋል",
  MANDATORY_SAVING: "ናይ ግዴታ ዕቋር?",
  TERM_DEPOSIT: "ውሱን ኣታዊ?",
  AUTO_CREATE_SHARE: "ናይ ዕፃ ሒሳብ ባዕሉ ይፈጠር?",
  SELECT_PRODUCT_CATAGORY: "ናይ ምህርቲ መደብ ይምረፁ",
  SELECT_SHARE_PRODUCT: "ዝደልዩዎ ናይ ዕፃ ሒሳብ ውፅኢት ይምረፁ",
  CURRENT_TERM: "ናይ ሐዚ ክፍሊት ይምረፁ",
  REPAYMENT: "ክፍሊት",
  REMAINING: "ቀሪ",
  PAY_VIA_CASH: "ብጥረ-ገንዘብ ይኽፈሉ?",
  PAY_VIA_CASH_INFO: "ከፋሊት ከፋሊ ብኣካል ተረኺቦም ብዘቕርብዎ ጥረ-ገንዘብ  ይኽፈል።",
  BANK_PAYMENT: "ናይ ባንኪ ክፍሊት?",
  BANK_PAYMENT_INFO: "ክፍሊት ብባንክታት እዩ ተፈፂሙ።",
  CHANGE_LANGUAGE: "ቋንቋ ይለውጡ።",
  INPUT: "እታዎት",
  SUPPORTS_JOIN_ACCOUNT: "ናይ ሓባር/ጣምራ ሒሳብ ይፍቀድ እዩ።",
  SUPPORTS_LOAN: "ናይ ልቓሕ ሒሳብ ይፍቀድ እዩ።",
  SUPPORTS_OVERDRAFT: "ልዕሊ ኣብ ሒሳብ ዘሎ መጠን ምውፃእ ይፍቀድ እዩ።",
  SUPPORTS_TRANSFER: "ካብ ሒሳብ ናብ ካሊእ ሒሳብ ምምሕልላፍ ይፍቀድ እዩ።",
  SUPPORTS_WITHDRAWAL: "ካብ ሒሳብ ወፃኢ ምግባር ይፍቀድ እዩ።",
  SUPPORTS_INTEREST_NEGOTATION: "ናይ ወለድ ሬት ድርድር ይፍቀድ እዩ።",
  IS_TERM_DEPOSIT: "ናይ ውሱን ዕቁር ይፍቀድ ድዩ?",
  IS_MANDATORY: "ናይ ግዴታ ዕቁር ይፍቀድ ድዩ?",
  ONLY_FOR_MEMBER: "ንኣባል ጥራሕ ድዩ",
  INTEREST_FREE: "ነፃ ወለድ",
  IS_FIXED_DEPOSIT: "ውሱን ዕቋር ድዩ",
  IS_GOAL_ORIENTED: "ዕላማ-ተኮር ድዩ",
  AUTO_CREATE_SHARE_ACC: "ናይ ዕፃ ሒሳብ ባዕሉ ይፈጠር",
  ENABLE_DORMANCY_TRACKING: "ከይተንቀሳቐሰ ዝፀንሐ (ድቁስ) ሒሳብ ምክትታል የኽእል",
  ELIGIBILITY_TYPE: "ዓይነት ብቑዕነት",
  MIN_AGE: "ዝተሓተ ዕድመ",
  MAX_AGE: "ዝለዓለ ዕድመ",
  MIN_TERM: "ዝተሓተ ግዜ ወሰን",
  MAX_TERM: "ዝለዓለ ግዜ ወሰን",
  INTEREST_CONFIGURATION: "ናይ ወለድ ምስትኽኻላት",
  PAYMENT_TERMS: "ናይ ክፍሊት ግዜ ወሰን",
  MIN_OPENING_BALANCE: "ዝተሓተ ሒሳብ መኽፈቲ መጠን",
  LABEL_INACTIVE_AFTER: "ድሕሪ ዝስዕብ መዓልቲ ዘይንጡፍ ይኹን",
  LABEL_DORMANT_AFTER: "ድሕሪ ዝስዕብ መዓልቲ ድቁስ ሒሳብ ይኹን",
  MIN_BALANCE: "ዝተሓተ ቀሪ ሒሳብ",
  DEPOSIT_FREQUENCY: "ኣታዊ ናይ ምግባር ድግግም (ብመዓልቲ)",
  APPLICABLE_FOR: "ተፈፃሚ ዝኾን",
  INTEREST_ACCURAL_GL: "ወለድ መዋህለሊ GL",
  INTEREST_INCOME_GL: "ናይ ወለድ ኣታዊ ዝቕመጠሉ GL",
  INTEREST_EXPENSE_GL: "ናይ ወለድ ወፃኢ ዝቕመጠሉ GL",
  TOTAL_INTEREST_RATE: "ናይ ወለድ ሚኢታዊ (ድምር)",
  INTEREST_RATE_CUSTOMER: "ናይ ወለድ ሚኢታዊ (ዓሚል)",
  INTEREST_RATE_COMPANY: "ናይ ወለድ ሚኢታዊ (ትካል)",
  TOTAL_SHARE: "ጠቕላላ ዕፃ",
  MIN_SHARE: "ዝተሓተ ዕፃ",
  MAX_SHARE: "ዝለዓለ ዕፃ",
  NOMINAL_PRICE: "መልዐሊ ዋጋ",
  SHARES_TOBE_ISSUED: "ክዕደሉ ዝኽእሉ ዕፃታት",
  CAPITAL_VALUE: "ካፒታል ዋጋ",
  MINIMUM_PERIOD: "ዝተሓተ ክፍለ-ግዜ (ብኣዋርሕ)",

  tig: "ትግ",
  PAYROLL: "ፔይሮል",
  COUNT: "ቁፅሪ",
  ATTENDANCE: "ATTENDANCE",
  CONFIG: "መስተካከሊ",
  DEPARTMENT: "ክፍሊ",
  EMPLOYEE: "ሰራሕተኛ",
  EMPLOYEES: "ሰራሕተኛታት",
  ADD_EMPLOYEE: "ሰራሕተኛ ይወስኹ",
  SALARY: "ደመወዝ",
  SALARIES: "ደመወዛት",
  SCALE: "ዕብየት",
  JOB_TITLE: "ናይ ስራሕ መዓርግ",
  DEPOSITES: "ኣታዊታት",
  WITHDROWS: "ወፃኢታት",
  CLASSES: "መደባት",
  PROFILE: "ስእሊ",
  PERMANENT: "ቀዋሚ",
  GROSS_SALARY: "ጠቅላላ ደመወዝ",
  SCALE_SALARY: "ዕብየት ደመወዝ",
  SCALES: "ዕብየት",
  TAX_INCOME: "ናይ ቀረፅ ኣታዊ",
  PENSION_RETIREMENT: "ናይ መደቀሲ ጥሮታ",
  COMPONENT: "ወሰኽ/ተቀናሲ ደመወዝ",
  EMPLOYEE_COMPONENT: "ወሰኽ/ተቀናሲ ደመወዝ ሰራሕተኛ",
  ACTIVITY_LOG: "ንጥፈታት",
  ALL_TIME: "ኩሉ ግዜ",
  THIS_YEAR: "ናይዚ ዓመት",
  THIS_MONTH: "ናይዚ ወርሒ",
}
